### ISSUE TITLE
Can't locate admin config panel

### ISSUE THREAD

**Issue by AxxaGroup** [nmarcy-del/m2-AdminUiColorTheme#6]
Don't know if it's just me but seems to be installed right but I can't for the life of me find where the config panel is in the admin end.

Obviously exists, there is a screenshot but is not where i'd expect it to be in Stores > Configuration.

Any help appreciated!!!

**Comment by nmarcy-del** [comment]
Hi,

I've made some test on a fresh magento installation and it seem's that in some case colorpicker library doesn't load properly, I've made some change and will create a new version right after.

Also can you please tell me wich version of php and magento you use thanks ?

Configuration is on Stores > Configurations > DEL001 > AdminTheme (see screenshoot below) : 

![image](https://github.com/nmarcy-del/m2-AdminUiColorTheme/assets/77853867/d4fdd7f2-de3b-4246-ab33-458d5c05d633)

Regards,

**Comment by AxxaGroup** [comment]
I'm using the latest, Magento 2.4.6 and PHP 8.2.

As you can see they're nothing showing in the admin area. I'm in developer mode and everything has been rebuilt since anyway so it's not that.

Let me know how you get on! Would be a nice module to use!

![Screenshot 2023-08-11 at 8 11 55 PM](https://github.com/nmarcy-del/m2-AdminUiColorTheme/assets/133702691/3a8bb64a-ddee-4233-ba4d-db36d6fba839)

**Comment by nmarcy-del** [comment]
Hi,

1.0.2 version has been release.

I've just try on magento 2.4.6 with php 8.2 seem's work as attempt.

Maybe try to do a composer remove del001/admin-ui-color-swap and then composer require del001/admin-ui-color-swap again. Then clean the cache and do a setup:upgrade (if module was added as theme will change after page refresh)

Regards,

**Comment by AxxaGroup** [comment]
Great. Working perfectly now!!!

Thanks for the update.

![Screenshot 2023-08-14 at 11 34 39 AM](https://github.com/nmarcy-del/m2-AdminUiColorTheme/assets/133702691/351198f8-9214-468b-84f0-505d6dd880ad)

**Comment by nmarcy-del** [comment]
Hi,

Thank you for your response. I consider this question resolved. If you have any further questions in the future, feel free to ask. Have a great day!

Regards,
